# Rename this file as configs.yaml to use.
db:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: 000000
  schema: gol_c
  charset: utf8mb4
email:
  user: tommy1995@163.com
  pass: t0mmy123
  host: smtp.163.com
  port: 465
  sign: ockham-api
email_validation:
  expire_duration: 30m
auth:
  session:
    expire_seconds: 7200
    maximum_renewal_times: 3
  jwt:
    issuer: ockham-api
    secret: aSyIjIQnv1LT7zEnSv0A # Use your own random password
    expire_seconds: 1800
  signature:
    timestamp_tolerance_seconds: 60