# Rename this file as configs.yaml to use.
db:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: 000000
  schema: gol_c
  charset: utf8mb4
email:
  user: tommy1995@163.com
  pass: t0mmy123
  host: smtp.163.com
  port: 465
  sign: gol-c
