// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/email-validations/any/validating": {
            "put": {
                "tags": [
                    "auth"
                ],
                "summary": "ValidateEmail",
                "parameters": [
                    {
                        "description": "Email validation from",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ValidateEmailJsonForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/auth/sessions": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login json form",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LoginJsonForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/auth/sessions/any/renewing": {
            "put": {
                "tags": [
                    "auth"
                ],
                "summary": "Keep login status",
                "parameters": [
                    {
                        "description": "session renewal form",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RenewSessionForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/auth/users": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "CreateUser from",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RegisterJsonForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/auth/users/me": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get Current User",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/auth/users/{user_id}/roles": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Grant Role",
                "parameters": [
                    {
                        "description": "GrantRoleForm from",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GrantRoleForm"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/auth/users/{user_id}/roles/{role_id}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Revoke Role",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "role id",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/recharge-codes/none/batch-generations": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "recharge_code"
                ],
                "summary": "Generate Recharge Codes in Batches",
                "parameters": [
                    {
                        "description": "Generating recharge code from",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RechargeCodeGeneratingJsonForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/service-plans": {
            "get": {
                "description": "Get all service plans",
                "tags": [
                    "market"
                ],
                "summary": "Get all service plans",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create service plan",
                "tags": [
                    "market"
                ],
                "summary": "Create service plan",
                "parameters": [
                    {
                        "description": "Create service plan form",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ServicePlanForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/service-plans/{service_plan_id}": {
            "get": {
                "description": "Get service plan",
                "tags": [
                    "market"
                ],
                "summary": "Get service plan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "service plan id",
                        "name": "service_plan_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/users/me/service-plan-subscriptions": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "List service plan subscriptions",
                "tags": [
                    "market"
                ],
                "summary": "List service plan subscriptions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Subscribes service plan",
                "tags": [
                    "market"
                ],
                "summary": "Subscribes service plan",
                "parameters": [
                    {
                        "description": "Subscribes service plan form",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SubscribeServicePlanForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/users/me/service-plan-subscriptions/{service_plan_subscription_id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get service plan subscriptions",
                "tags": [
                    "market"
                ],
                "summary": "Get service plan subscriptions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "service plan subscriptions id",
                        "name": "service_plan_subscription_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/users/me/wallet": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Get wallet info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/users/me/wallet/recharging": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Recharge",
                "parameters": [
                    {
                        "description": "Recharge form",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RechargeForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        },
        "/v1/users/me/wallet/records": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Get wallet records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.Pack"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "util.Meta": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "util.Pack": {
            "type": "object",
            "properties": {
                "body": {},
                "meta": {
                    "$ref": "#/definitions/util.Meta"
                }
            }
        },
        "v1.GrantRoleForm": {
            "type": "object",
            "properties": {
                "roleID": {
                    "type": "integer"
                }
            }
        },
        "v1.LoginJsonForm": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.RechargeCodeGeneratingJsonForm": {
            "type": "object",
            "properties": {
                "batchCount": {
                    "type": "integer"
                },
                "packageName": {
                    "type": "string"
                },
                "rechargeAmount": {
                    "type": "number"
                }
            }
        },
        "v1.RechargeForm": {
            "type": "object",
            "properties": {
                "rechargeCode": {
                    "type": "string"
                }
            }
        },
        "v1.RegisterJsonForm": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.RenewSessionForm": {
            "type": "object",
            "properties": {
                "renewalKey": {
                    "type": "string"
                }
            }
        },
        "v1.ServicePlanForm": {
            "type": "object",
            "properties": {
                "eachTermInheritSurplusTraffic": {
                    "description": "循环中继承结余流量",
                    "type": "boolean"
                },
                "eachTermTrafficBytes": {
                    "description": "每次循环的流量大小",
                    "type": "integer"
                },
                "planDescription": {
                    "description": "描述",
                    "type": "string"
                },
                "planEnabled": {
                    "description": "启用中",
                    "type": "boolean"
                },
                "planTitle": {
                    "description": "标题",
                    "type": "string"
                },
                "renewalFee": {
                    "description": "每次循环价格",
                    "type": "number"
                },
                "termSpacingDays": {
                    "description": "循环周期",
                    "type": "integer"
                },
                "termTimesTotal": {
                    "description": "总循环次数",
                    "type": "integer"
                }
            }
        },
        "v1.SubscribeServicePlanForm": {
            "type": "object",
            "properties": {
                "consolidateBillings": {
                    "description": "合并账单一次结清",
                    "type": "boolean"
                },
                "servicePlanId": {
                    "type": "integer"
                }
            }
        },
        "v1.ValidateEmailJsonForm": {
            "type": "object",
            "properties": {
                "validatorCode": {
                    "type": "string"
                },
                "validatorKey": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "Ockham API",
	Description: "All APIs of Ockham Project",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
