basePath: /api
definitions:
  v1.LoginJsonForm:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  v1.RegisterJsonForm:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  v1.ValidateEmailJsonForm:
    properties:
      validatorCode:
        type: string
      validatorKey:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: All APIs of Gol-C Project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gol-C API
  version: "1.0"
paths:
  /v1/auth/email-validation/validate:
    put:
      description: Validate a user's email
      parameters:
      - description: Email validation from
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.ValidateEmailJsonForm'
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: ValidateEmail
  /v1/auth/sessions:
    post:
      description: Login as a user
      parameters:
      - description: CreateSession from
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.LoginJsonForm'
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Login
  /v1/auth/users:
    post:
      description: Register to create a user
      parameters:
      - description: CreateUser from
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.RegisterJsonForm'
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Register
swagger: "2.0"
