basePath: /api
definitions:
  util.Meta:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  util.Pack:
    properties:
      Meta:
        $ref: '#/definitions/util.Meta'
      data:
        type: object
    type: object
  v1.LoginJsonForm:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  v1.RechargeCodeGeneratingJsonForm:
    properties:
      batchCount:
        type: integer
      packageName:
        type: string
      rechargeAmount:
        type: number
    type: object
  v1.RechargeForm:
    properties:
      rechargeCode:
        type: string
    type: object
  v1.RegisterJsonForm:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  v1.RenewSessionForm:
    properties:
      renewalKey:
        type: string
    type: object
  v1.ValidateEmailJsonForm:
    properties:
      validatorCode:
        type: string
      validatorKey:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: All APIs of Gol-C Project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gol-C API
  version: "1.0"
paths:
  /v1/auth/email-validations/any:validate:
    put:
      description: Validate a user's email
      parameters:
      - description: Email validation from
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.ValidateEmailJsonForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Pack'
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/util.Pack'
      summary: ValidateEmail
      tags:
      - auth
  /v1/auth/sessions:
    post:
      description: Login as a user
      parameters:
      - description: Login json form
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.LoginJsonForm'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/util.Pack'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.Pack'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/util.Pack'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Pack'
      summary: Login
      tags:
      - auth
  /v1/auth/sessions/any:renew:
    put:
      description: Keep login status as a user.
      parameters:
      - description: session renewal form
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.RenewSessionForm'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/util.Pack'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/util.Pack'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/util.Pack'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Pack'
      summary: Keep login status
      tags:
      - auth
  /v1/auth/users:
    post:
      description: Register to create a user
      parameters:
      - description: CreateUser from
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.RegisterJsonForm'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/util.Pack'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/util.Pack'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Pack'
      summary: Register
      tags:
      - auth
  /v1/recharge-codes/none/batch-generations:
    post:
      description: Generate Recharge Codes in Batches
      parameters:
      - description: Generating recharge code from
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.RechargeCodeGeneratingJsonForm'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/util.Pack'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/util.Pack'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Pack'
      security:
      - Bearer: []
      summary: Generate Recharge Codes in Batches
      tags:
      - recharge_code
  /v1/service-plans:
    get:
      description: Get all service plans
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Pack'
      summary: Get all service plans
      tags:
      - market
  /v1/users/me/wallet:
    get:
      description: Get wallet info
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Pack'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Pack'
      security:
      - Bearer: []
      summary: Get wallet info
      tags:
      - wallet
  /v1/users/me/wallet/records:
    get:
      description: Get wallet records
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Pack'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Pack'
      security:
      - Bearer: []
      summary: Get wallet records
      tags:
      - wallet
  /v1/users/me/wallet:recharge:
    put:
      description: Register to create a user
      parameters:
      - description: Recharge form
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.RechargeForm'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/util.Pack'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/util.Pack'
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/util.Pack'
      security:
      - Bearer: []
      summary: Recharge
      tags:
      - wallet
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
